In [1]:
import pandas as pd

In [3]:
sample = pd.read_json('dataset.json')

In [4]:
sample

                  type                                           features
0    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
1    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
2    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
3    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
4    FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
..                 ...                                                ...
193  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
194  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
195  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
196  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...
197  FeatureCollection  {'type': 'Feature', 'properties': {'WARD_NO': ...

[198 rows x 2 columns]

In [16]:
df = pd.json_normalize(sample['features'])

In [17]:
df.head(5)

,type,properties.WARD_NO,properties.WARD_NAME,properties.MOVEMENT_ID,properties.DISPLAY_NAME,geometry.type,geometry.coordinates
0,Feature,2,Chowdeswari Ward,1,"Unnamed Road, Bengaluru",MultiPolygon,"[[[[77.5922939, 13.0971962], [77.5909447, 13.0..."
1,Feature,3,Atturu,2,"9th Cross Bhel Layout, Adityanagar, Vidyaranya...",MultiPolygon,"[[[[77.5686203, 13.1270495], [77.5706371, 13.1..."
2,Feature,4,Yelahanka Satellite Town,3,"15th A Cross Road, Yelahanka Satellite Town, Y...",MultiPolygon,"[[[[77.5909447, 13.0984219], [77.5922939, 13.0..."
3,Feature,51,Vijnanapura,4,"SP Naidu Layout 4th Cross Street, SP Naidu Lay...",MultiPolygon,"[[[[77.6768275, 13.0114668], [77.6769546, 13.0..."
4,Feature,53,Basavanapura,5,"Medahalli Kadugodi Road, Bharathi Nagar, Krish...",MultiPolygon,"[[[[77.728993, 13.0206055], [77.7299353, 13.01..."

In [18]:
df.isnull().sum()

type                       0
properties.WARD_NO         0
properties.WARD_NAME       0
properties.MOVEMENT_ID     0
properties.DISPLAY_NAME    0
geometry.type              0
geometry.coordinates       0
dtype: int64